# Generated by Django 2.2.7 on 2019-11-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(max_length=64)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('num_claims', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('firstnamed_assignee_id', models.PositiveIntegerField(blank=True, null=True)),
                ('firstnamed_assignee_persistent_id', models.CharField(blank=True, max_length=36, null=True)),
                ('firstnamed_assignee_location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('firstnamed_assignee_persistent_location_id', models.CharField(blank=True, max_length=128, null=True)),
                ('firstnamed_assignee_city', models.CharField(blank=True, max_length=128, null=True)),
                ('firstnamed_assignee_state', models.CharField(blank=True, max_length=20, null=True)),
                ('firstnamed_assignee_country', models.CharField(blank=True, max_length=10, null=True)),
                ('firstnamed_assignee_latitude', models.FloatField(blank=True, null=True)),
                ('firstnamed_assignee_longitude', models.FloatField(blank=True, null=True)),
                ('firstnamed_inventor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('firstnamed_inventor_persistent_id', models.CharField(blank=True, max_length=36, null=True)),
                ('firstnamed_inventor_location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('firstnamed_inventor_persistent_location_id', models.CharField(blank=True, max_length=128, null=True)),
                ('firstnamed_inventor_city', models.CharField(blank=True, max_length=128, null=True)),
                ('firstnamed_inventor_state', models.CharField(blank=True, max_length=20, null=True)),
                ('firstnamed_inventor_country', models.CharField(blank=True, max_length=10, null=True)),
                ('firstnamed_inventor_latitude', models.FloatField(blank=True, null=True)),
                ('firstnamed_inventor_longitude', models.FloatField(blank=True, null=True)),
                ('num_foreign_documents_cited', models.PositiveIntegerField()),
                ('num_us_applications_cited', models.PositiveIntegerField()),
                ('num_us_patents_cited', models.PositiveIntegerField()),
                ('num_total_documents_cited', models.PositiveIntegerField()),
                ('num_times_cited_by_us_patents', models.PositiveIntegerField()),
                ('earliest_application_date', models.DateField(blank=True, null=True)),
                ('patent_processing_days', models.PositiveIntegerField(blank=True, null=True)),
                ('uspc_current_mainclass_average_patent_processing_days', models.PositiveIntegerField(blank=True, null=True)),
                ('cpc_current_group_average_patent_processing_days', models.PositiveIntegerField(blank=True, null=True)),
                ('term_extension', models.PositiveIntegerField(blank=True, null=True)),
                ('detail_desc_length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patent',
                'managed': False,
            },
        ),
    ]
