# Generated by Django 2.2.7 on 2019-11-14 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('patent_id', models.CharField(max_length=20)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(blank=True, max_length=64, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'application',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('assignee_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('name_first', models.CharField(blank=True, max_length=64, null=True)),
                ('name_last', models.CharField(blank=True, max_length=64, null=True)),
                ('organization', models.CharField(blank=True, max_length=256, null=True)),
                ('num_patents', models.PositiveIntegerField()),
                ('num_inventors', models.PositiveIntegerField()),
                ('lastknown_location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lastknown_persistent_location_id', models.CharField(blank=True, max_length=128, null=True)),
                ('lastknown_city', models.CharField(blank=True, max_length=128, null=True)),
                ('lastknown_state', models.CharField(blank=True, max_length=20, null=True)),
                ('lastknown_country', models.CharField(blank=True, max_length=10, null=True)),
                ('lastknown_latitude', models.FloatField(blank=True, null=True)),
                ('lastknown_longitude', models.FloatField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField()),
                ('persistent_assignee_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'assignee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssigneeCpcGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_id', models.PositiveIntegerField()),
                ('group_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'assignee_cpc_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssigneeCpcSubsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_id', models.PositiveIntegerField()),
                ('subsection_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'assignee_cpc_subsection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssigneeInventor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_id', models.PositiveIntegerField()),
                ('inventor_id', models.PositiveIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'assignee_inventor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssigneeNberSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_id', models.PositiveIntegerField()),
                ('subcategory_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'assignee_nber_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssigneeUspcMainclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_id', models.PositiveIntegerField()),
                ('mainclass_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'assignee_uspc_mainclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssigneeYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee_id', models.PositiveIntegerField()),
                ('patent_year', models.SmallIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'assignee_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=36)),
                ('patent_id', models.CharField(blank=True, max_length=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('dependent', models.IntegerField(blank=True, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('exemplary', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'claim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcCurrent',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('section_id', models.CharField(blank=True, max_length=10, null=True)),
                ('subsection_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subsection_title', models.CharField(blank=True, max_length=512, null=True)),
                ('group_id', models.CharField(blank=True, max_length=20, null=True)),
                ('group_title', models.CharField(blank=True, max_length=256, null=True)),
                ('subgroup_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup_title', models.CharField(blank=True, max_length=512, null=True)),
                ('category', models.CharField(blank=True, max_length=36, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('num_assignees_group', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors_group', models.PositiveIntegerField(blank=True, null=True)),
                ('num_patents_group', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date_group', models.DateField(blank=True, null=True)),
                ('last_seen_date_group', models.DateField(blank=True, null=True)),
                ('years_active_group', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cpc_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcCurrentCopy',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('section_id', models.CharField(blank=True, max_length=10, null=True)),
                ('subsection_id', models.CharField(blank=True, max_length=20, null=True)),
                ('group_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=36, null=True)),
            ],
            options={
                'db_table': 'cpc_current_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcCurrentGroup',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('section_id', models.CharField(blank=True, max_length=10, null=True)),
                ('group_id', models.CharField(max_length=20)),
                ('group_title', models.CharField(blank=True, max_length=512, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cpc_current_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcCurrentGroupApplicationYear',
            fields=[
                ('group_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('application_year', models.PositiveSmallIntegerField()),
                ('sample_size', models.PositiveIntegerField()),
                ('average_patent_processing_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cpc_current_group_application_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcCurrentGroupCopy',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('section_id', models.CharField(blank=True, max_length=10, null=True)),
                ('group_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cpc_current_group_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcCurrentGroupPatentYear',
            fields=[
                ('group_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patent_year', models.PositiveSmallIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cpc_current_group_patent_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcCurrentSubsection',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('section_id', models.CharField(blank=True, max_length=10, null=True)),
                ('subsection_id', models.CharField(max_length=20)),
                ('subsection_title', models.CharField(blank=True, max_length=512, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cpc_current_subsection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcCurrentSubsectionCopy',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('section_id', models.CharField(blank=True, max_length=10, null=True)),
                ('subsection_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cpc_current_subsection_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcCurrentSubsectionPatentYear',
            fields=[
                ('subsection_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patent_year', models.PositiveSmallIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'cpc_current_subsection_patent_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcGroup',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cpc_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcSubgroup',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'cpc_subgroup',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CpcSubsection',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cpc_subsection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('examiner_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(blank=True, max_length=64, null=True)),
                ('name_last', models.CharField(blank=True, max_length=64, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('persistent_examiner_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'examiner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Foreignpriority',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('foreign_doc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=64, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'foreignpriority',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GovernmentInterest',
            fields=[
                ('patent_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('gi_statement', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'government_interest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GovernmentOrganization',
            fields=[
                ('organization_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('level_one', models.CharField(blank=True, max_length=255, null=True)),
                ('level_two', models.CharField(blank=True, max_length=255, null=True)),
                ('level_three', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'government_organization',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('inventor_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(blank=True, max_length=64, null=True)),
                ('name_last', models.CharField(blank=True, max_length=64, null=True)),
                ('num_patents', models.PositiveIntegerField()),
                ('num_assignees', models.PositiveIntegerField()),
                ('lastknown_location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lastknown_persistent_location_id', models.CharField(blank=True, max_length=128, null=True)),
                ('lastknown_city', models.CharField(blank=True, max_length=128, null=True)),
                ('lastknown_state', models.CharField(blank=True, max_length=20, null=True)),
                ('lastknown_country', models.CharField(blank=True, max_length=10, null=True)),
                ('lastknown_latitude', models.FloatField(blank=True, null=True)),
                ('lastknown_longitude', models.FloatField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField()),
                ('persistent_inventor_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'inventor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventorCoinventor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventor_id', models.PositiveIntegerField()),
                ('coinventor_id', models.PositiveIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inventor_coinventor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventorCpcGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventor_id', models.PositiveIntegerField()),
                ('group_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inventor_cpc_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventorCpcSubsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventor_id', models.PositiveIntegerField()),
                ('subsection_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inventor_cpc_subsection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventorNberSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventor_id', models.PositiveIntegerField()),
                ('subcategory_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inventor_nber_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventorRawinventor',
            fields=[
                ('uuid', models.AutoField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(blank=True, max_length=64, null=True)),
                ('name_last', models.CharField(blank=True, max_length=64, null=True)),
                ('patent_id', models.CharField(blank=True, max_length=20, null=True)),
                ('inventor_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventor_rawinventor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventorUspcMainclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventor_id', models.PositiveIntegerField()),
                ('mainclass_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inventor_uspc_mainclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InventorYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventor_id', models.PositiveIntegerField()),
                ('patent_year', models.SmallIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inventor_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ipcr',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=20, null=True)),
                ('ipc_class', models.CharField(blank=True, max_length=20, null=True)),
                ('subclass', models.CharField(blank=True, max_length=20, null=True)),
                ('main_group', models.CharField(blank=True, max_length=20, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=20, null=True)),
                ('symbol_position', models.CharField(blank=True, max_length=20, null=True)),
                ('classification_value', models.CharField(blank=True, max_length=20, null=True)),
                ('classification_data_source', models.CharField(blank=True, max_length=20, null=True)),
                ('action_date', models.DateField(blank=True, null=True)),
                ('ipc_version_indicator', models.DateField(blank=True, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ipcr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name_first', models.CharField(blank=True, max_length=64, null=True)),
                ('name_last', models.CharField(blank=True, max_length=64, null=True)),
                ('organization', models.CharField(blank=True, max_length=256, null=True)),
                ('num_patents', models.PositiveIntegerField()),
                ('num_assignees', models.PositiveIntegerField()),
                ('num_inventors', models.PositiveIntegerField()),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField()),
                ('persistent_lawyer_id', models.CharField(max_length=36)),
            ],
            options={
                'db_table': 'lawyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('county', models.CharField(blank=True, max_length=60, null=True)),
                ('state_fips', models.CharField(blank=True, max_length=2, null=True)),
                ('county_fips', models.CharField(blank=True, max_length=3, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('num_assignees', models.PositiveIntegerField()),
                ('num_inventors', models.PositiveIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
                ('persistent_location_id', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationAssignee',
            fields=[
                ('location_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('assignee_id', models.PositiveIntegerField()),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location_assignee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationCpcGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveIntegerField()),
                ('group_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'location_cpc_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationCpcSubsection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveIntegerField()),
                ('subsection_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'location_cpc_subsection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationInventor',
            fields=[
                ('location_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('inventor_id', models.PositiveIntegerField()),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'location_inventor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationNberSubcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveIntegerField()),
                ('subcategory_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'location_nber_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationUspcMainclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveIntegerField()),
                ('mainclass_id', models.CharField(max_length=20)),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'location_uspc_mainclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocationYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.PositiveIntegerField()),
                ('year', models.SmallIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'location_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nber',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category_title', models.CharField(blank=True, max_length=512, null=True)),
                ('subcategory_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subcategory_title', models.CharField(blank=True, max_length=512, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nber',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NberCategory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'nber_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NberCopy',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('category_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subcategory_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'nber_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NberSubcategory',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nber_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NberSubcategoryPatentYear',
            fields=[
                ('subcategory_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patent_year', models.PositiveSmallIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'nber_subcategory_patent_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(max_length=64)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('num_claims', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('firstnamed_assignee_id', models.PositiveIntegerField(blank=True, null=True)),
                ('firstnamed_assignee_persistent_id', models.CharField(blank=True, max_length=36, null=True)),
                ('firstnamed_assignee_location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('firstnamed_assignee_persistent_location_id', models.CharField(blank=True, max_length=128, null=True)),
                ('firstnamed_assignee_city', models.CharField(blank=True, max_length=128, null=True)),
                ('firstnamed_assignee_state', models.CharField(blank=True, max_length=20, null=True)),
                ('firstnamed_assignee_country', models.CharField(blank=True, max_length=10, null=True)),
                ('firstnamed_assignee_latitude', models.FloatField(blank=True, null=True)),
                ('firstnamed_assignee_longitude', models.FloatField(blank=True, null=True)),
                ('firstnamed_inventor_id', models.PositiveIntegerField(blank=True, null=True)),
                ('firstnamed_inventor_persistent_id', models.CharField(blank=True, max_length=36, null=True)),
                ('firstnamed_inventor_location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('firstnamed_inventor_persistent_location_id', models.CharField(blank=True, max_length=128, null=True)),
                ('firstnamed_inventor_city', models.CharField(blank=True, max_length=128, null=True)),
                ('firstnamed_inventor_state', models.CharField(blank=True, max_length=20, null=True)),
                ('firstnamed_inventor_country', models.CharField(blank=True, max_length=10, null=True)),
                ('firstnamed_inventor_latitude', models.FloatField(blank=True, null=True)),
                ('firstnamed_inventor_longitude', models.FloatField(blank=True, null=True)),
                ('num_foreign_documents_cited', models.PositiveIntegerField()),
                ('num_us_applications_cited', models.PositiveIntegerField()),
                ('num_us_patents_cited', models.PositiveIntegerField()),
                ('num_total_documents_cited', models.PositiveIntegerField()),
                ('num_times_cited_by_us_patents', models.PositiveIntegerField()),
                ('earliest_application_date', models.DateField(blank=True, null=True)),
                ('patent_processing_days', models.PositiveIntegerField(blank=True, null=True)),
                ('uspc_current_mainclass_average_patent_processing_days', models.PositiveIntegerField(blank=True, null=True)),
                ('cpc_current_group_average_patent_processing_days', models.PositiveIntegerField(blank=True, null=True)),
                ('term_extension', models.PositiveIntegerField(blank=True, null=True)),
                ('detail_desc_length', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatentAssignee',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('assignee_id', models.PositiveIntegerField()),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'patent_assignee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatentExaminer',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('examiner_id', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'patent_examiner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatentGovintorg',
            fields=[
                ('patent_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'patent_govintorg',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatentInventor',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('inventor_id', models.PositiveIntegerField()),
                ('location_id', models.PositiveIntegerField(blank=True, null=True)),
                ('sequence', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'patent_inventor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatentLawyer',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lawyer_id', models.PositiveIntegerField()),
                ('sequence', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'patent_lawyer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pctdata',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=2)),
                ('doc_number', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('number_102_date', models.DateField(blank=True, db_column='102_date', null=True)),
                ('number_371_date', models.DateField(blank=True, db_column='371_date', null=True)),
            ],
            options={
                'db_table': 'pctdata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'post_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usapplicationcitation',
            fields=[
                ('citing_patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('cited_application_id', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('kind', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'usapplicationcitation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uspatentcitation',
            fields=[
                ('citing_patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('cited_patent_id', models.CharField(blank=True, max_length=20, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'uspatentcitation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UspcCurrent',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('mainclass_id', models.CharField(blank=True, max_length=20, null=True)),
                ('mainclass_title', models.CharField(blank=True, max_length=256, null=True)),
                ('subclass_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subclass_title', models.CharField(blank=True, max_length=512, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uspc_current',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UspcCurrentCopy',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('mainclass_id', models.CharField(blank=True, max_length=20, null=True)),
                ('subclass_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'uspc_current_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UspcCurrentMainclass',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mainclass_id', models.CharField(max_length=20)),
                ('mainclass_title', models.CharField(blank=True, max_length=256, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uspc_current_mainclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UspcCurrentMainclassApplicationYear',
            fields=[
                ('mainclass_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('application_year', models.PositiveSmallIntegerField()),
                ('sample_size', models.PositiveIntegerField()),
                ('average_patent_processing_days', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uspc_current_mainclass_application_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UspcCurrentMainclassCopy',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mainclass_id', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'uspc_current_mainclass_copy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UspcCurrentMainclassPatentYear',
            fields=[
                ('mainclass_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patent_year', models.PositiveSmallIntegerField()),
                ('num_patents', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'uspc_current_mainclass_patent_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UspcMainclass',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('num_patents', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inventors', models.PositiveIntegerField(blank=True, null=True)),
                ('num_assignees', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen_date', models.DateField(blank=True, null=True)),
                ('last_seen_date', models.DateField(blank=True, null=True)),
                ('years_active', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uspc_mainclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UspcSubclass',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'db_table': 'uspc_subclass',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wipo',
            fields=[
                ('patent_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('field_id', models.CharField(blank=True, max_length=3, null=True)),
                ('sequence', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'wipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WipoField',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('sector_title', models.CharField(blank=True, max_length=60, null=True)),
                ('field_title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'wipo_field',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatentContractawardnumber',
            fields=[
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='backend_2.GovernmentInterest')),
                ('contract_award_number', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'patent_contractawardnumber',
                'managed': False,
            },
        ),
    ]
